### ISSUE TITLE
페북로그인과 쿠키에 관련된 질문!

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#100]
네아로는 세션으로 관리하는데
페북로그인은 쿠키로 관리하는 이유가 있나요??

혹시 세션으로 변경하면 안되나해서..ㅎㅎ

**Comment by 2daebong** [comment]
변경하고픈 이유는 뭔가요?

**Comment by probitanima11** [comment]
네이버 로그인(고객로그인) 여부는 세션으로 LoginInterceptor에서 확인했는데요
페북 로그인(관리자로그인) 여부도 세션으로 같은 방법으로 관리하기 위해서 입니다.

**Comment by probitanima11** [comment]
우선 쿠키는 기존 그대로 두고
로그인 시 세션을 생성하는 방법으로 해결하였습니다.
