### ISSUE TITLE
item이라는 용어와 product라는 용어의 통일

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#110]
대부분의 코드에서 item(아이템)을 사용하는데
admin의 한 곳에서 product(상품)를 사용합니다.

개발 코드에서는 크게 의미가 다르지 않는데
디자인/기획/개발의 협업시 용어정리를 위해서는 
개인적으로 product(상품)이라고 하는게 좀 더 명시적일 것 같아요.

정리하면 
1. product, 상품 이라고 사용할 지
2. item, 아이템 이라고 사용할 지 
(골라골라ㅎㅎ)

의견주세요.

**Comment by 2daebong** [comment]
(뜨끔)
방금 코드보다가 admin에 product라고 되어 있길래 
바꿀까..하다가 나중에해야지 했는데 ㅋㅋㅋㅋ 
내가 바꿀게
DB테이블과 Entity에 item이라고 되어 있으니 
item으로 통일하는게 좋을듯 ㅎ

**Comment by jason-hwang** [comment]
저도 item으로 하는게 좋을거 같은 생각이 드네요. (그냥)
ㅋㅋㅋㅋ

**Comment by probitanima11** [comment]
ㅋㅋ 좋습니다 그럼 대봉햄께 어사인걸어놓을게요~

**Comment by probitanima11** [comment]
https://github.com/Helibrothers/dico-server/pull/114 로 해결되어 close하겠습니다.
