### ISSUE TITLE
2차 오프라인 미팅 이슈 리스팅

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#112]
## 2차 오프라인 미팅 이슈 리스팅
일자 : 2월 19일 예정?

리스팅하고 싶은 논의주제는 댓글로 ㄱㄱ

각자 세미나 주제
대범 : 애자일
성현 : AOP (feat. interceptor) 로그인 세션 관리 https://github.com/Helibrothers/dico-server/issues/36
재성 : 프론트엔드 gulp, require로 배포 자동화 및 디펜던시 모듈 관리하기

**Comment by 2daebong** [comment]
#111 API 네이밍 논의 + Rest API 논의

**Comment by probitanima11** [comment]
https://github.com/Helibrothers/dico-server/issues/36 interceptor vs AOP - 로그인 세션 관리

**Comment by 2daebong** [comment]
@probitanima11 @jason-hwang 
이번 오프라인 미팅 일요일 어떤가?

**Comment by jason-hwang** [comment]
으음 괜찮긴 할거 같아요 ㅋㅋ 세미나 주제 내꺼도 정해야되죠?

으음... 프론트엔드 gulp, require로 배포 자동화 및 디펜던시 모듈 관리하기?

**Comment by probitanima11** [comment]
헛 일요일이요? 약속 없었는데 선약이 잡혀브렀어여ㅠㅠ

**Comment by probitanima11** [comment]
다음주 일욜 저녁은 가능합니당ㅎㅎ

**Comment by 2daebong** [comment]
##미팅 결과

1. 디자인 관련 이슈
	ㄱ. 소개페이지 작업
		- BE : 성현
		- FE : 재성
	ㄴ. 배너 작업
		- FE : 재성 (링크는 톡톡으로 연결)
	ㄷ. 아이콘
		- iOS : 대범
		- 안드, 웹 : 재성


2. 개발 이슈

	대범 
	1. 도메인 따고 코드에 반영 
	2. 주문페이지
	3. 버그 수정(멀티 업로드)
	4. 상품 구성 (리얼 DB)
	
	성현
	1. 도메인 따지면 주소 사용 마무리 + DB 작업
	2. 소개 페이지 백단 작업
	3. 로그인 화면 개선
	4. BE 장바구니 뱃지

	재성
	1. FE 작업 (소개페이지, 배너, 아이콘)
	2. 안드로이드 작업 (아이콘 도메인 저장)
	3. 디자이너와 커뮤니케이션 + 메인 페이지 개선
	4. FE 장바구니 뱃지

	공통
	버그 잡기


2. 디자인

**Comment by jason-hwang** [comment]
해당 작업들 완료되었고, 
새로운 이슈 수정은 다음 이슈를 통해 계속 진행됨 #185
