### ISSUE TITLE
오프라인 미팅에 스터디를 추가하면 어떨까?

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#113]
우리의 목적은 헬리콥터도 있지만 재미와 성과를 더한 개인+팀프로젝트를 함으로써 
스스로의 역량향상에도 목적이 있어!! 굉장히 중요한 부분임.

좀 더 도움이 되기위해
오프라인 미팅때 업무 이야기 외에 주제하나씩 선정해서 이를 공부해오고 공유하면 어떨까 하는데 ㅋㅋ
대신 주제는 쌩뚱맞은게 아니라,
우리가 이 코드에서 직접 사용하고 있는 부분들.
예를 들면
- #111 RestAPI
- (직접 사용하는건 아니지만 내가 공부하려했던, 도입해볼 수 있을까 했던..) #96 애자일,스크럼,칸반
- 아니면 그냥 JPA 써보니까 이렇더라!! 라던지
- (이런거도 재밌을 것 같은데) 우린 인터셉터를 썼어!! AOP로 바꾸면??

그냥 무턱대고 이런 주제를 하나씩 잡아서 짧게든 길게든 공유하면 서로에게 많은 도움이 되지 않을까 ㅎㅎ
회사에서 자바 스터디하는거보다는 잘 와닿고 우리가 했던 부분을 한번 더 곱씹을수도 있고.. 다른사람이 담당해서 몰랐던 부분을 잘 알 수 있을것 같은데!

**Comment by jason-hwang** [comment]
생산적인 활동 좋죠 ㅎㅎㅎ 아는걸 공유해도 되고 주제를 잡아서 공부해와서 공유해도 되구요~

**Comment by probitanima11** [comment]
맞아요 각자 주제를 하나씩 정해서 공부한 다음 **전파세미나** 하는 방식으로 하는게 시간을 아낄 수 있을 것 같아요ㅎㅎ

**Comment by jason-hwang** [comment]
전파세미나 오랜만에 듣네 ㅋㅋㅋㅋㅋ

**Comment by 2daebong** [comment]
그럼 매 세미나마다 하나씩 주제를 정하자 
나는 애자일이란 도대체 무엇인가에 대해 하겠음

**Comment by probitanima11** [comment]
세명의 동의가 있었으니 close해도 될 것 같네용ㅎㅎ
