### ISSUE TITLE
디자이너님 피드백 기록

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#117]
생각나는대로 추가하면 좋을 것 같아요~
이 목록 중 하나씩 이슈 등록해서 처리해나갑시다 ㅎㅎ

* 상단바 배너 가리지 않게 하기
* 버튼은 클릭할 수 있도록 사이즈 조절하기
* 홈 화면을 제외한 화면의 상단에 back버튼 넣기(+아이폰 하단 메뉴바 제거)
* 상품 목록화면의 아이템 글자 크기 키우기
* 로그인화면 개선하기
  * 네이버 계정으로 로그인 해야한다는 안내 이미지(or 문구) 넣기
  * 안내 이미지(or 문구) 아래로 네이버 로그인 버튼 내리기

**Comment by jason-hwang** [comment]
넵 ㅋㅋ 금방 처리하도록 해보져 ㅎㅎㅎ

**Comment by 2daebong** [comment]
@jason-hwang 
디자이너분 슬랙 초대하장 
새로 채널 파도 되고 원래 있던 디자인 채널에 초대해도 되고 ㅎ

**Comment by jason-hwang** [comment]
초대해드렸는데 안들어오시네요 ㅋㅋㅋㅋ 다시 보내드려야겠음
