### ISSUE TITLE
3차 오프라인 미팅 [2017. 2. 2]

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#119]
참석자 : 공, @probitanima11 @jason-hwang, @2daebong

논의한 내용 여기에 정리

**Comment by probitanima11** [comment]
1. 장바구니 화면에서 주소지 나오게 하기
2. 앱에서 하단 메뉴바 제거 및 뒤로가기 버튼 위치 수정
3. 장바구니에서 주문하기 화면으로 간 후 주문 완료가 되도록 하기
4. 상품 사진 올려주기
5. 장바구니 버튼 위치 수정하기
등등 ..

**Comment by probitanima11** [comment]
![image](https://cloud.githubusercontent.com/assets/4353846/22791465/ce1408d4-ef2c-11e6-8db1-228b0a85f616.png)

**Comment by probitanima11** [comment]
회의한 내용 이슈등록 or 해결처리 되어서 이 이슈는 닫겠습니다.
