### ISSUE TITLE
개인정보취급방침 & 이용약관 추가

### ISSUE THREAD

**Issue by jason-hwang** [Helibrothers/dico-server#122]
1. 이용약관(전자상거래 표준)
http://www.ftc.go.kr/info/bizinfo/stdContractView.jsp?std_agrmt_no=490&currpage=1&searchKey=1&searchVal=%C0%FC%C0%DA%BB%F3%B0%C5%B7%A1&stdate=&enddate=

2. 개인정보처리방침 만들기
https://www.privacy.go.kr/a3sc/per/inf/perInfStep01.do

개인정보처리방침의 경우 기관정보가 확정되어야 사용 가능

<img width="680" alt="screen shot 2017-02-05 at 12 08 06 pm" src="https://cloud.githubusercontent.com/assets/4724172/22623365/cdc371d8-eb9b-11e6-9bee-da2f14d849f8.png">

<전체 정리 참고>
http://library.gabia.com/contents/homepage/3076

**Comment by probitanima11** [comment]
음 이것도 필요하군요!

![2017-02-06 2 41 08](https://cloud.githubusercontent.com/assets/4353846/22635875/55eca41a-ec7a-11e6-8019-f775826177dc.png)

**Comment by probitanima11** [comment]
이거 완료된것 맞나요?

**Comment by jason-hwang** [comment]
이용약관은 만들어져있고, 개인정보처리방침만 만들면 됩니다. (URL이 확정되어야 해서 보류되고 있었음)

**Comment by jason-hwang** [comment]
[#개인정보처리방침 작성 예시](https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwiPk5HAyajSAhUGhrwKHXQyAoQQFgglMAE&url=https%3A%2F%2Fwww.privacy.go.kr%2Fcmm%2Ffms%2FFileDown.do%3FatchFileId%3DFILE_000000000072233%26fileSn%3D1%26nttId%3D1767&usg=AFQjCNGzqhs4zCPrBhNTOTueGtbAGd7WhA&sig2=MTWN0FAzLphRVxCcXTTZew)

**Comment by jason-hwang** [comment]
- 개인정보처리방침의 경우 다음 항목에 대해 변경사항이 있을 경우 업데이트 필요.

4. 개인정보 항목 선택(필수항목)
만약 새로운 정보가 추가로 필요하게 될 경우, 항목 수정 필요. (4. 처리하는 개인정보의 항목 작성)
![screen shot 2017-02-24 at 8 04 18 pm](https://cloud.githubusercontent.com/assets/4724172/23336857/b9b0f546-fc1f-11e6-81e3-babd1ed06164.png)

6. 개인정보의 안전성 확보조치
기술적으로 다 조치된 사항인지 향후 검토 필요
![screen shot 2017-02-26 at 12 01 13 pm](https://cloud.githubusercontent.com/assets/4724172/23336855/b1faa6e4-fc1f-11e6-928b-87afb335c089.png)

**Comment by jason-hwang** [comment]
이슈 작업 완료
