### ISSUE TITLE
배송지정보를 관리하는 새로운 Entity 생성 건의(UserInfo 대체)

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#124]
# 요약
- 기존에 embeddable로 선언되어 Delivery와 User에 사용되던 UserInfo를 별도의 entity로 분리에 대한 건의
- UserInfo라는 네이밍도 배송지라는 의미를 가진 이름으로 수정 건의

# 건의배경
- UserInfo에 사용되던 배송지정보가 늘어남
  - 기존에는 String 하나에서 행정구역코드, 위도, 경도 등 이 포함됨
- 이렇게 되면 Delivery와 User의 필드도 늘어나게 됨
  - 같은 분류의 데이터지만 다른 테이블에 위치하게 됨
- 배송지정보를 의미하는 정보끼리 모아두면 좋을 것 같음

# 수정작업
- UserInfo대신 Location(가칭)이라는 Entity 생성 및 테이블 생성
- Delivery와 User에 UserInfo정보였던 폰넘버(String)와 주소(String)가 제거되고
- Location(가칭)의 ID만 들어감

**Comment by 2daebong** [comment]
이부분만 ERD로 그려서 볼 수 있을깡?

**Comment by probitanima11** [comment]
@2daebong 넵! 오늘 퇴근하고 올려놓을께요

**Comment by probitanima11** [comment]
![s__5496845](https://cloud.githubusercontent.com/assets/4353846/22781750/4ae68a60-ef07-11e6-8b80-b34cfb77e7cd.jpg)

**Comment by probitanima11** [comment]
1. Order과 Delivery 테이블 합치기
2. Location 테이블 추가하기
- userId 필드 포함

으로 결정되서 작업하겠습니당ㅎㅎ
