### ISSUE TITLE
커밋메시지 한글로 작성해도 깨지지않게 하기

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#13]

**Comment by 2daebong** [comment]
한글로 커밋작성해보니 되네 -.- 
터미널의 인코딩을 UTF-8로 설정하니 되는거 같음..
@jason-hwang 
재성아 너도 해봐 ㅋㅋ

**Comment by jason-hwang** [comment]
저는 UTF-8로 이미 설정되있던데 ㅎㅎㅎ 커밋을 한글로 안해봐서 허허

**Comment by probitanima11** [comment]
ㅋㅋㅋㅋ 그러면 한글 쓸 때는 UTF-8로 설정해서 쓰는걸로 하고 close 하것습니다ㅋㅋㅋ
