### ISSUE TITLE
헬리팜 소개 페이지 FE작업

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#137]
@jason-hwang 
https://github.com/Helibrothers/dico-server/pull/133 이거 이어서 진행하면 됨 !!

**Comment by jason-hwang** [comment]
<중간 상황 공유>

- 메뉴(햄버거) 버튼 위치 변경
- 장바구니 아이콘 변경
- 배너 이미지 변경
- 장바구니 뱃지 기능 추가
뱃지 기능 때문에 세션에 장바구니 담겨있는 개수를 추가 해뒀는데... 좋은 방법 있으면 공유해주세용

![screen shot 2017-02-28 at 1 47 07 am](https://cloud.githubusercontent.com/assets/4724172/23370393/dad25cfe-fd57-11e6-8571-704d6cca800e.png)

**Comment by jason-hwang** [comment]
- 화면 Touch시 Pointer 효과 추가
이건 한번 실험적으로 넣어본 기능인데, 아무래도 WebApp이라 클릭했을때 화면과 살짝 이질감이 든다 해야하나.. 그래서 한번 추가해봤어요.
- 꼭 포인터가 아니더라도, 먼가 인터랙션한 효과가 필요하긴 할듯...

![pointer](https://cloud.githubusercontent.com/assets/4724172/23370459/1a7906d2-fd58-11e6-8377-d04bc4f23723.gif)

**Comment by jason-hwang** [comment]
해당 이슈 닫고 개별 이슈로 진행
