### ISSUE TITLE
사이드메뉴 > 사용자 이름이 ID로 노출됨

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#157]
# 문제되는 경우
kakao 계정일 경우 id가 userID가 아니라 유니크한 숫자가 저장됨

# 해결방법
* 1. Session에 User NickName을 넣어서 보여주기
* 2. 해당 부분 제거하기

**Comment by jason-hwang** [comment]
아 카카오는 그렇게 받아올 줄 몰랐네. 이름은 따로 세션에 안넣어둬서 괜찮다고 생각했었는데..ㅎㅎ 이름으로 바로 보여주면 좋을듯 ㅋㅋ

**Comment by probitanima11** [comment]
이름으로 하려면 세션에 name도 같이 보관해서 노출하면 될 듯!ㅎㅎ
