### ISSUE TITLE
회원정보수정 > 화면 구성 질문

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#159]
아래의 빨간 영역에 문구가 좀 어색한 것 같고 빈 공간이 좀 넓지않나요?
빨간 영역 만큼 없어지면 좋을 것 같아서 의견 남깁니당ㅋㅋ

<img width="339" alt="2017-03-19 2 49 45" src="https://cloud.githubusercontent.com/assets/4353846/24078534/63e791f2-0cb3-11e7-82b4-f73e64e25c1f.png">

**Comment by jason-hwang** [comment]
아직 레이아웃이 전체적으로 가다듬어지지 않아서 ㅎㅎㅎ.. 공통으로 수정하려고 함.

**Comment by jason-hwang** [comment]
#153 이슈와 함께 수정됨
