### ISSUE TITLE
주문목록 > 마크업 깨짐

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#162]
# 마크업 깨지는 화면
* 주문목록
* 주문 디테일

# 재현화면
<img width="353" alt="2017-03-19 2 57 57" src="https://cloud.githubusercontent.com/assets/4353846/24078573/9812219e-0cb4-11e7-84e9-3239290119d5.png">

**Comment by jason-hwang** [comment]
<주문배송 조회 화면>
![screen shot 2017-04-03 at 9 36 02 am](https://cloud.githubusercontent.com/assets/4724172/24592401/0783ebfa-1851-11e7-9a09-d4fe7aa9518c.png)

**Comment by jason-hwang** [comment]
@2daebong @probitanima11 

주문배송 조회할때 최초로 리스트 받아오면 그때 시간이 꽤 걸리던데... (이후 요청은 캐시가 되는건지 빠름)
여기서는 페이지네이션 처리 필요할거 같은데, 어떤가요?
옥션이나 11번가 같은거 봐도... 주문내역 조회 1~3개월만 가능하다거나 제약이 많던데.
