### ISSUE TITLE
상단 네비 바에 이전 버튼 존재 하도록 수정

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#177]
개편이후 기존과 다르게 상단 네비게이션 바에 이전 버튼이 항상 있는게 아니므로..
IOS에서 특정 페이지에서는 이전 화면으로 돌아갈 방법이 존재하지 않음
@jason-hwang 의견 주세요.

**Comment by jason-hwang** [comment]
추가할 얘정입니다~

**Comment by 2daebong** [comment]
네엡 확인감사. 이슈 닫을게요
