### ISSUE TITLE
4/10 미팅결과

### ISSUE THREAD

**Issue by jason-hwang** [Helibrothers/dico-server#191]
**<개발 개선 사항>**
- [x] Gzip compressor(코드 레벨) - 재성 
- [x] AWS S3 서버 이미지 캐시를 위해 cloudFront 도입 검토 - 대범
- [ ] 아이폰 앱 검토 + 개발 - 대범
	- 하드웨어 가속
	- 앱 아이콘 변경
	- 아이폰 앱 내에서 더블 탭 이벤트 받지 않도록 수정.

**<UX & 설계 개선 사항>**
- [x] 단위 수정 (고정단위 -> 자유롭게 할 수 있도록) - 성현
- [x] 카테고리 추가 -> 베스트.  - 성현
- [x] 상품 우선순위 어드민에서 결정할 수 있도록. - 성현
- [x] 메인 카테고리 명 옆에 더보기 추가. - 재성
- [x] 카트 페이지에서 배송비 할인 중이라는 것 알 수 있도록 표시 - 재성
- [x] 카트 담기 버튼 영역 넓히기
- [x] 사이트 검색 확인 - 성현
- [x] 어드민 상품 페이지 리스팅 된 상태에서 가격 수정 바로 가능하도록 (진행중) - 성현

**<버그>**
- [x] 축산/달걀 탭에 상품 하나 등록되어 있는데 메인에서는 보이지 않음. - 재성

**Comment by 2daebong** [comment]
버그 리포트

메인에서 담기 버튼 동작 영역이 너무 작음.
=> 카트 아이콘만 탭이 가능하며 나머지 영역에는 반응 하지 않음.
탭 영역을 수정 가능 할 지 검토 필요

**Comment by probitanima11** [comment]
담기버튼 영역 넓혀야할듯요!

**Comment by jason-hwang** [comment]
담기버튼 영역 넓히기 완료

**Comment by probitanima11** [comment]
<img width="747" alt="2017-04-19 1 53 17" src="https://cloud.githubusercontent.com/assets/4353846/25142747/009974c8-24a3-11e7-8885-838b233dd501.png">
