### ISSUE TITLE
주문 내역 확인 기능 개발

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#2]
- 주문 확인 메뉴
- 주문 페이지

**Comment by 2daebong** [comment]
이게 시급한데 ㅎㅎ 이걸 내가 먼저 개발할께~

**Comment by jason-hwang** [comment]
중요한건뎅 자꾸 자잘한게 눈에 들어와서 먼저 처리해버렸네요 ㅎㅎ

**Comment by 2daebong** [comment]
@probitanima11 성현아 오늘 slack으로 얘기한 이슈임 ~ 부탁함 ㅎㅎ

**Comment by probitanima11** [comment]
엇 혹시 지금 이 기능 구현되어있나요?
/orderList ??

**Comment by jason-hwang** [comment]
@probitanima11 그때 대봉이형이 진행하겠다고 했었는데..
@2daebong 대봉이형 혹시 레이아웃 안짰으면 제가 할까요?

**Comment by probitanima11** [comment]
레이아웃이 짜여있는거 같길래 근데 로직은 안짜여있는거 같길래 @_@
그럼 대봉햄 답오기 전까지 일단 보류

**Comment by 2daebong** [comment]
@jason-hwang @probitanima11 
/orderList 는 하나의 주문에 대한 상세내역이고..
전체 주문을 볼 수 있는 리스트 페이지도 하나 있어야될거같네

상단 메뉴 바 -> 주문내역 -> 주문상품 페이징으로 출력 -> 주문 선택하면 저 /orderList(이름바꿔야할듯)으로 이동하도록 ㅎㅎ 일이 많네 생각보다 -.-

**Comment by probitanima11** [comment]
@jason-hwang @2daebong 

# 주문목록 vs 주문내역
- /orderList : 주문목록
- /orderList/{orderId} : 주문 하나의 내역

# 화면 내용
- 주문목록은 admin에 있는거처럼 하면 될까요?
- 주문내역은 기존 화면을 하면 될 것 같아용ㅋㅋ

이렇게 하면 될까요?

**Comment by 2daebong** [comment]
엄청빨리했군 ㅋㅋ 아주 잘하셨습니다. 굳굳
관련 이슈 두개 등록했슴당
#45 #44
