### ISSUE TITLE
상품 노출 개선

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#21]
메인에 노출할 상품들을 유연하게 컨트롤 가능하도록 개선 필요.

## Task
- [ ] Paging
- [ ] 우선순위 부여

**Comment by probitanima11** [comment]
혹시 메인에 노출 할 상품 규칙 정해진 것 있나요?

**Comment by 2daebong** [comment]
아니 규칙은 따로 없고.. 지금으로도 충분한데.. 상품이 엄청나게 많은 경우 페이징 + 우선순위를 줘서 운영자가 원하는 순서대로 배치 할 수 있도록 해야하지 않을까?

**Comment by probitanima11** [comment]
음 페이징은 필요할 것 같아요 
1차적으로 페이징 적용해 놓고
2차로 우선순위를 줄 수 있도록 진행하는건 어떨까요?

**Comment by 2daebong** [comment]
좋아 ! 근데 문제는 아직 서비스에서 페이징의 필요성을 못느끼는거...... 
일단 상품부터 쫙 등록해두고 오픈부터 해볼까?ㅋㅋ

**Comment by jason-hwang** [comment]
상품 풀 리스트를 정리한번 해둬야겠네요

**Comment by 2daebong** [comment]
경률이 돌아오면 상품 정리해서 올려야될것 같애 
+ 메인 배너도 교체하고 ㅋㅋ @jason-hwang 상품 상세 페이지 이쁘게 만드는게 우선순위가 높은거같은데~ㅋㅋ
나는 어드민 배너 교체하는 작업부터 시작할게

**Comment by jason-hwang** [comment]
@2daebong 네 허허 알겠어요

**Comment by 2daebong** [comment]
세부 이슈로 전환됨
페이징 : #42 
레이어 : #43
