### ISSUE TITLE
제플린 적용해보기

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#213]
기간별 매출 그래프 그리기
매장 개념 도입 이후에는 매장 별 매출 그래프 그리기도 해보기

**Comment by probitanima11** [comment]
우선 로컬에서 시도 해 보았습니다.
https://github.com/Helibrothers/dico-server/wiki/Apache-Zeppelin

**Comment by jason-hwang** [comment]
네 좋습니다.

**Comment by 2daebong** [comment]
넹

**Comment by probitanima11** [comment]
서버 메모리 부족으로 설치가 안되여ㅠㅠ
이 이슈는 서버 증설 이후로 재검토 하겠습니다
<img width="1273" alt="2017-06-30 2 03 51" src="https://user-images.githubusercontent.com/4353846/27982949-28d953b2-63ec-11e7-95d2-ff0e3b8c7c87.png">
<img width="528" alt="2017-06-30 2 04 08" src="https://user-images.githubusercontent.com/4353846/27982950-2b7915e4-63ec-11e7-8c80-f266f35a8e98.png">
