### ISSUE TITLE
메인 UI 개선

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#24]
<img width="316" alt="2016-12-01 2 06 43" src="https://cloud.githubusercontent.com/assets/13724323/20762780/e585be76-b76a-11e6-8a55-61a6a76b3193.png">

이게 정녕 사진의 문제란 말인가....
대책이 필요하다

**Comment by probitanima11** [comment]
height 고정하면 안되나용?ㅋㅋ

**Comment by jason-hwang** [comment]
해당 이슈는 사진의 가로 세로 비율이 다를 경우 (사이즈 말고) 나타나는데, 네이버의 경우에도 항상 동일한 비율 & 고정된 크기로 뿌려주고 있음.
만~약에 나중에 관리자가 사진을 폰으로 찍어서 업로드하고, 물품을 추가할 수 있게 된다면...
1. 업로드할 때 서버쪽에서 섬네일용 이미지 crop하도록 짜거나
2. Front에서 꼼수를 쓰거나 
둘 중 하나로 처리해야겠네요 ㅎㅎ

**Comment by jason-hwang** [comment]
https://github.com/Helibrothers/dico-server/pull/30 Front에서 어느정도 보완하여 패치 반영함
(이미지를 Center cropped 하였음. 아래 링크 참고)
http://jonathannicol.com/blog/2014/06/16/centre-crop-thumbnails-with-css/
