### ISSUE TITLE
ModelAndView가 컨벤션인가요?

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#26]
컨트롤러의 메소드 리턴타입이 (@ResponseBody제외하고) 대부분 ModelAndView인데요
혹시 String으로 하면 가독성이 (아주)조금 올라갈 것 같아서 한번 제안해봅니다.

```java
@RequestMapping(value = "/admin/test", method = RequestMethod.GET)
public ModelAndView test() {
    ModelAndView mv = new ModelAndView();
    mv.addObject("items", itemService.findItems());
    mv.setViewName("admin/test");
    return mv;
}
```
```java
@RequestMapping(value = "/admin/test", method = RequestMethod.GET)
public String test(Model model) {
    model.addAttribute("items", itemService.findItems());
    return "admin/test";
}
```

(참고로 String으로 리턴타입을 해도 결국 나중에는 ModelAndView로 변하긴 합니다)
[참고](http://bistros.tistory.com/entry/%EC%8A%A4%ED%94%84%EB%A7%81MVC%EC%97%90%EC%84%9C-return-type%EC%9D%B4-String-%EC%9D%BC%EA%B2%BD%EC%9A%B0)

**Comment by 2daebong** [comment]
좋아여 좋아 ㅎㅎ 적극 찬성입니다.

`public String test(Model model) {`
모델이 파라미터로 들어오네 ㅋㅋ 얘는 어떻게 들어오는거지
정확하게 얘네 동작을 알았으면 좋겠는데 ㅋㅋ 소스좀 까보고 공유할까
(할수있으려나)

**Comment by probitanima11** [comment]
네! 좋습니다 이런거 분석하는거 좋아합네다ㅋㅋㅋ

**Comment by probitanima11** [comment]
#27 로 진행하도록 하고 해당 이슈는 close 하겠습니다.
