### ISSUE TITLE
로그인 확인은 인터셉터로 분리해도 좋을것 같아요!

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#36]

**Comment by jason-hwang** [comment]
좋은 생각인거 같습니다~~ 지금은 메서드마다 체크해서 ㅎㅎㅎ

**Comment by probitanima11** [comment]
괜찮다면 제가 진행을...ㅋㅋ

**Comment by 2daebong** [comment]
@probitanima11 @jason-hwang 
오 좋아요 인터셉터 ㅎㅎ 
이왕 할거면 AOP?? 공부하면서 적용하면 좋지않을까 ㅎ

**Comment by 2daebong** [comment]
(사실 나도 아직 AOP 개념이.. 어려워..)

**Comment by probitanima11** [comment]
토비책에서 AOP만 따로 때서 공부해보면 좋을것 같네용ㅋㅋ
