### ISSUE TITLE
contributor에 성현이가 없다!!!!

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#37]
contributor에 성현이가 없다!!!!
contributor에 성현이가 없다!!!!
contributor에 성현이가 없다!!!!
contributor에 성현이가 없다!!!!
contributor에 성현이가 없다!!!!
contributor에 성현이가 없다!!!!
contributor에 성현이가 없다!!!!

로컬 계정이랑 github이랑 연동이 안된것 같은데?!
profile에 키 하나 등록해서 연결 ㄱㄱ

**Comment by probitanima11** [comment]
설명이 필요합니다! (이해를 못했어요..ㅎㅎ)

**Comment by jason-hwang** [comment]
커밋 많이 하는데 왜 컨트리뷰터에 보면 내역이 없다 나오지 이상하네

**Comment by 2daebong** [comment]
<img width="1041" alt="2016-12-17 12 38 44" src="https://cloud.githubusercontent.com/assets/13724323/21284136/dfa19afa-c455-11e6-9984-1436867b4c16.png">


여기 보면 성현이만 없음 ㅎㅎ 
로컬계정이랑 github 계정이랑 연동해야돼
소스트리나 터미널에 설정을 해야함

난 터미널 쓰고 github계정에 ssh key 해서 쓴당ㅎ

**Comment by jason-hwang** [comment]
음 저도 GitHub 계정 ssh key 등록돼 있는데 이거 안해줘서 그런가 ㅎㅎ

**Comment by probitanima11** [comment]
등록했슴당ㅋㅋ  이제 나올 꺼에용ㅎㅎ
