### ISSUE TITLE
어드민 FE 리팩토링 + 기능개선

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#38]
## 어드민 FE 리팩토링 + 기능개선

* task
- [ ] 리팩토링 : 어드민 상품 업로드 script 모듈화
- [ ] 기능개선 : 이미지 업로드 크기 지정 (오픈소스사용)

## 리팩토링 : 어드민 상품 업로드 script 모듈화
현재 어드민-상품 페이지에 붙어있는 이미지 업로드 기능이 상품페이지 뿐만 아니라 여러곳에서 필요해요.
모듈화(라이브러리화)가 되어서 여기저기서 사용할 수 있으면 생산성이 높아질 것 같네요.
```
이미지 업로드 기능
아마존 S3 서버 사용 인증은 페이스북 로그인+토큰 사용
```

## 기능개선 : 이미지 업로드 크기 지정 (오픈소스사용)
현재 이미지를 업로드한테 사이즈+종횡비 제한이 없음.
이미지를 업로드 할때 조절할 수 있으면 좋을것 같은데..
전부 구현하긴 쉽지 않으니 오픈소스를 찾아보면 좋을 것 같네.

**Comment by 2daebong** [comment]
@jason-hwang 조금 큰 작업 같은데 잘 부탁드립니다.ㅎ

**Comment by jason-hwang** [comment]
현재 이미지 뿌려줄 때 종횡비 제한에 상관없이 중앙에 배치되도록 css가 반영되어 있어서 괴랄한(?) 비율의 사진이 아닌 이상 무리 없이 잘 보여질거에요. 이미지 업로드 크기 지정하는건 필요한 기능은 맞음.
