### ISSUE TITLE
주기적인 오프라인 코딩 어떨까?

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#40]
@jason-hwang 제안인데 ㅎㅎ 
격주단위로 주말중 하루정도 즉 2주에 하루정도 
모여서 같이 놀고 먹으면서 코딩하면 어떨까 싶은데 ㅎㅎ 

* 위치
* 매주 스케쥴 잡기.. (고정? 동적으로?)

정도 확인해야 될거같은데 ㅎ
위치는 카페? 스터디룸? 아니면 우리집? ㅋㅋ 
뭐 어디든 ㅋㅋ 

일단 각자 의견을 모아보자

나는 좋은거 같음!

**Comment by jason-hwang** [comment]
ㅋㅋㅋ저는 적극 찬성이요 처음에 집에서 빈둥빈둥하는게 좋다 생각했는데 이게 10시간 대충 한거랑 1-2시간 버닝에서 하는거링 비슷하더라구요 (게으른 제 성격상) ㅋㅋㅋ

**Comment by probitanima11** [comment]
저도 완전 찬성!!

**Comment by probitanima11** [comment]
일단 한번 모여봅시다! 저의 환영식 겸ㅋㅋㅋㅋ

**Comment by 2daebong** [comment]
오키 그럼.. 이번주 일정부터 볼까?
나는 토요일 약속있고 일요일 됨!!

**Comment by jason-hwang** [comment]
일요일 괜춘할거 같아요 ㅋㅋ

**Comment by probitanima11** [comment]
오키 일욜!ㅋㅋ

**Comment by 2daebong** [comment]
오키 근데 어디서 하지 ㅋㅋ 좀 편한 분위기 속에서 먹고 놀만한 작업실이 있으면 좋겠는데 ㅋㅋ 
우리집 괜찮은데 ㅋㅋ 진근이가 이사 오는 날이라 .. 한 4시 ?? 정도부터 될거 같은데

**Comment by probitanima11** [comment]
토즈같은데 잡고 하면 비쌀까요?ㅎㅎ
