### ISSUE TITLE
어드민 - 상품 삭제 버그

### ISSUE THREAD

**Issue by jason-hwang** [Helibrothers/dico-server#41]
현재 삭제가 안되는 이슈가 있네요..
(신규 상품 등록, 기존 상품 업데이트는 문제 없이 잘 작동하네용)

**Comment by jason-hwang** [comment]
쿼리를 보니 다른 주문 테이블에 엮여있어서 그런거였군요..

**Comment by 2daebong** [comment]
FK 걸려있어서 그런건가 ㅋㅋ 드디어 JPA에 벽에 부딪히는건가 ㅋ

**Comment by 2daebong** [comment]
#49 이슈로 전환됨
