### ISSUE TITLE
배너 엔드 : 이벤트 페이지

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#46]
상단 배너를 clickable 하게 하고 해당 엔드 페이지 구성

템플릿화 하면 좋을 것 같음.
추후에 상단 배너 뿐만 아니라 상품 노출 중간에도 배너가 필요할 것 같음...

설계 필요.

내가 진행하려 하는데 혹시 관심있는 사람 같이 논의해도 됨 ㅎㅎ 커멘트 ㄱㄱ

**Comment by probitanima11** [comment]
https://github.com/Helibrothers/dico-server/issues/3 이 이슈와 중복인가요?
