### ISSUE TITLE
네아로 한글 도메인 등록 이슈 확인

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#47]
현재 우리가 사용하는 도메인

dicoadmin.com
www.dicoadmin.com
야채사요.com
www.야채사요.com

1. 네아로에서 멀티 도메인이 등록되는지 확인.
2. 멀티 도메인이 등록 안된다면 한글 도메인(야채사요.com) 을 쓸수 없는지 확인
3. 만약 쓸수없다면 새로운 도메인 파야될듯

**Comment by jason-hwang** [comment]
네이버 담당자 답변에 의하면
1. 현재 멀티 도메인 지원하지 않음
(서브 도메인인은 지원 *.naver.com)
http://forum.developers.naver.com/t/port/10277

2. 한글 도메인 지원 함
http://forum.developers.naver.com/t/topic/7367

따라서....
한글 도메인 쓰려면 
App 새로 파서 Client, Secret key 키 따로 가져가는 것으로 해야함

아니면 도메인을 새로 파고
domain.com >> 일반 사용자
admin.domain.com >> 어드민식으로 사용하거나 해야 할 듯.

**Comment by 2daebong** [comment]
@jason-hwang 
굳입니다

멀티 도메인까진 필요 없을 것같고
지금 우리 어드민에 네아로랑 연관이 없으니
어드민은 그대로 사용하고
네아로에는 한글도메인(www.야채사요.com , 야채사요.com)만 등록해서 하면 될듯ㅎㅎ

메신저로 얘기했던 백단에서 redirect url 관련된 값만 확인해줘~!

**Comment by jason-hwang** [comment]
- 야채사요.com
- www.야채사요.com
도메인 등록 완료 (로그인 테스트 완료)
================================================
네이버 Developer Site에서는 퓨니코드(?) 적용했어요..!!
야채사요.com
==> xn--vf4b11gbyam0o.com

좀 의아했던건 www.야채사요.com / 야채사요.com 둘다 지원하기 위해서

http://xn--vf4b11gbyam0o.com/naverOauthCallback
http://www.xn--vf4b11gbyam0o.com/naverOauthCallback

둘다 등록 해줘야 됐다는 점~~

**Comment by probitanima11** [comment]
오! 한글도메인 완성ㅋㅋ

**Comment by jason-hwang** [comment]
이슈 닫아도 되겠네요 ㅎㅎ
