### ISSUE TITLE
아이폰 하이브리드 앱 개발

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#48]
<img width="375" alt="2016-12-27 1 18 07" src="https://cloud.githubusercontent.com/assets/13724323/21484218/68edb842-cbd2-11e6-8e25-e9f6b24e64e9.png">

- [x] 앱 개발
- [x] 개발자등록
- [x] 기기 등록
- [x] 개발할 앱 연결과 권한
- [x] 앱 심사를 위한 준비
- [x] 배포 요청
- [x] 리젝당하기
- [x] 다시 제출
- [x] 승인!

**Comment by 2daebong** [comment]
개발자등록 요청 완료. 12만9천원 결제.. ㅎㄷㄷ 깡패들..

**Comment by jason-hwang** [comment]
그것도 1년 단위라니 참... 구글은 평생 무료인뎁

**Comment by 2daebong** [comment]
![2016-12-28 1 34 00](https://cloud.githubusercontent.com/assets/13724323/21503889/cd5c513c-cc9d-11e6-9489-d73ba52cb33f.png)

ios 앱 제출 준비 완료. ㅋㅋ

![2016-12-28 12 49 47](https://cloud.githubusercontent.com/assets/13724323/21503891/d65d38c8-cc9d-11e6-8bec-da03389d1982.png)

이 깡패들이 지네 쉰다고 앱 제출도 안받음 ㅎㅎ

**Comment by 2daebong** [comment]
뚜루루.. 리젝...

```
2017년 1월 4일 오전 4:32
Apple의 메시지
2. 1 PERFORMANCE: APP COMPLETENESS
Performance - 2.1


Your app or its metadata does not appear to include final content. Specifically, your App Description states:

야채사요 Application 입니다..

Next Steps

Please review your app and metadata to ensure that all of its content is final.

Since your iTunes Connect status is Metadata Rejected, we do NOT require a new binary. To revise the metadata, visit iTunes Connect to select your app and revise the desired metadata values. Once you’ve completed all changes, reply to this message in Resolution Center and we will continue the review.

NOTE: Please be sure to make any metadata changes to all app localizations by selecting each specific localization and making appropriate changes.
```

**Comment by probitanima11** [comment]
뚜루루...ㅠㅠ

**Comment by 2daebong** [comment]
파파고의 번역 위엄(그렇다고 영어로 해서 몰랐던건 아님ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ)

```
앱 또는 메타 데이터에는 최종 내용이 포함되어 있지 않습니다. 구체적으로, 앱 설명 상태는 다음과 같습니다.

야채사요 Application 입니다..

다음 단계

모든 콘텐츠가 최종적인 것인지 확인하기 위해 앱 및 메타 데이터를 검토하십시오.

당신의 아이튠즈 ConnectStatus가 메타 데이타 Rejected이기 때문에, 우리는 새로운 바이너리를 요구하지 않습니다. 메타 데이터를 수정하려면 iTunesConnecttoiTunes를 방문하여 앱을 선택하고 원하는 메타 데이터 값을 수정합니다. 모든 변경 사항을 완료하면 이 메시지에 대한 답변을 해결하고 검토를 계속하겠습니다.

참고:각각의 특정 변경 사항을 선택하고 적절한 변경을 수행함으로써 모든 애플리케이션에 대한 메타 데이터를 변경할 수 있습니다.
```
도움 : 파파고 번역 http://labspace.naver.com/nmt/ (200자로 제한되어 있음. 200자를 넘어가면 성능이 잘 안나온다고 함)


### 결론
앱 소개 글이 못마땅한거 같은데.. 난 재성이가 구글플레이에 올렸던 앱 소개를 그대로 카피한건데 ㅋㅋ 
일단 소개글에 조금 더 세부적으로 상세하게 적어서 다시 제출해보겠음!

**Comment by 2daebong** [comment]
변경된 앱 소개 글
```
매일 새벽 직판장에서 직접 공수한 야채를 선택하면
한시간 이내에 집으로 배송됩니다!

매일 필요한 야채들! 
필요한 만큼 주문 한번이면 한시간 이내로 집으로 배송됩니다.
스마트한 헬리팜과 함께 시간절약! 돈 절약! 상품 질은 높이고!!

이용해보세요! 
(제공하는 지역은 점차 확대됩니다.)
```
(아이부끄러)
제출 완료~

**Comment by 2daebong** [comment]
아놔 다시 제출 할 필요없이 커멘트만 달면 된다고 했는데 ..
다시 제출해브렀네...망.....

**Comment by jason-hwang** [comment]
ㅋㅋㅋㅋ 느낌표.... 강렬하다 나도 업뎃 해놔야겠어요
