### ISSUE TITLE
상품 비노출 처리 가능하도록

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#49]
### 어드민 상품 삭제 불가 이슈 #41 

상품 삭제 불가능한 원인 : 해당 상품이 주문되어 주문에서 FK가 걸려있음.

해결 방안 : 주문 내역 확인을 위해 상품이 삭제되면 안됨. 하지만 판매하지 않는 상품일 수 있음.

-> 상품에 노출/비노출여부가 필요. DB 단에서 컬럼 생성 필요할 듯

**Comment by probitanima11** [comment]
remove써서 지우는거 대신 
노출여부 컬럼을 생성해서 이거 true/false로 판단해야겠네요..ㅎㅎㅎㅎㅎㅎㅎ
