### ISSUE TITLE
이벤트 바인딩 하는 부분이 여러군데 있는 것 같음

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#51]
### 현재 상황
app.js에서 바인딩 하는 경우가 있고
userInfo.jsp와 같은 jsp 파일에서 바인딩 되는 경우가 있음!

### 하나의 방식으로 통일 하면 좋을 것 같습니다!
- 바인딩을 모두 app.js에서 할 것인지
- 각 jsp에서 바인딩을 할 것인지

**Comment by jason-hwang** [comment]
피드백 처럼 기존의 app.js를 common.js 로 변경하고 global로 적용해야 하는 부분만 이벤트 바인딩하도록 수정해야 할 것 같네요 ㅎㅎ
얘기한 것 처럼 나머진 각 jsp에서 바인딩하면 될 것 같아 ㅋㅋ

**Comment by jason-hwang** [comment]
아, common.js 가 bootstrap 관련 기능으로 사용 중이니... global.js ? 등등 으로.. !!
