### ISSUE TITLE
[PC] 상단 바 메뉴 색깔이 잘 안보입니다

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#55]
## 최초화면 
<img width="1246" alt="2016-12-17 11 47 41" src="https://cloud.githubusercontent.com/assets/4353846/21283859/e1509934-c44e-11e6-8d9d-c597d07d2092.png">

## 스크롤 조금 내린 화면 
<img width="1248" alt="2016-12-17 11 47 55" src="https://cloud.githubusercontent.com/assets/4353846/21283868/2642c63e-c44f-11e6-8efc-15ffbe87d6ab.png">

**Comment by jason-hwang** [comment]
일단 PC화면은 조금 나중에 진행하는 걸로 해야 할 듯 ㅠ.ㅠ

**Comment by probitanima11** [comment]
구래용 ㅠ.ㅠ 그럼 묵혀두자ㅎㅎ

**Comment by jason-hwang** [comment]
#153 과 함께 PC화면 대응 완료
