### ISSUE TITLE
PC 레이아웃 수정 (반응형)

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#6]
PC 레이아웃 수정 (반응형)

**Comment by jason-hwang** [comment]
메인페이지에서 깨지지 않도록 수정하였음.
이외에도 주문, 장바구니, 로그인 화면에서 깨지지는 않지만 
모니터 가로 길이의 100%를 차지 하고 있으므로 수정 필요

**Comment by probitanima11** [comment]
PC 메인 페이지에서 주문 버튼 누를 시 팝업창이 화면 아래쪽에 배치 되어서 짤리는 현상이 있는 것 같음!!

**Comment by jason-hwang** [comment]
팝업창 짤리는 현상 수정 완료
https://github.com/Helibrothers/dico-server/pull/28

**Comment by jason-hwang** [comment]
https://github.com/Helibrothers/dico-server/pull/30 메인화면에서 카드 섹션 레이아웃 깨지는 현상 수정 완료

**Comment by jason-hwang** [comment]
(셀프 리뷰)PC화면에서 각 페이지 title 잘못 노출되는 문제 수정할 것

**Comment by jason-hwang** [comment]
#153과 함께 PC 대응 완료
