### ISSUE TITLE
stackoverflow랑 친해지기

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#66]
더 넓은 세상에서 많은 사람들이랑 소통하기 위해 ㅎㅎ
stackoverflow랑 친해지는 연습을 이제 꾸준히 하려고 하는데!!
stackoverflow는 평판(reputation) 기반이라 처음에 시작하기도 쉽지 않네 ㅎㅎ

http://stackoverflow.com/questions/41326285/is-there-way-to-see-a-all-requestmapping-urls-in-intellij-like-sts-requestmappi

이렇게 오늘 첫글을 올렸는데 ㅋㅋ 
혹시 이미 시작한 사람이나 관심있는 사람은 서로 글올리는거 봐주고 공유하면서 하면 좋을것 같음.ㅎㅎ

**Comment by 2daebong** [comment]
아 저 내글에 upvote도 한번씩 부탁드림다 ㅎㅎㅎㅎㅎㅎㅎㅎ

**Comment by probitanima11** [comment]
오오오오오 여기에 글 써볼 생각은 못해봤는데ㅋㅋㅋ 굿입니다ㅋㅋ

**Comment by 2daebong** [comment]
우리끼리 개발하다가 벽에 부딪히면 빨리빨리 해결해나가는 능력이 필요한데 
지금 우리는 회사에서 배우는거에만 의존되어 있어서 ㅋㅋ 
이런 곳에서 활동을 통해 더욱 성장이 필요할 듯 ㅎㅎ

**Comment by jason-hwang** [comment]
좋네요 적극 추진합시다

**Comment by 2daebong** [comment]
@probitanima11 @jason-hwang 
오키 그럼 둘다 stackoverflow에 가입해서 글 하나 남기는거부터 시작ㅎ
구글번역이 워낙 잘되어서 ㅎㅎㅎㅎㅎㅎㅎㅎ

**Comment by jason-hwang** [comment]
@2daebong 아니 파파고 왜 안 쓰세요 ㅋㅋㅋㅋ

**Comment by 2daebong** [comment]
@jason-hwang 그거 웹 없던데??ㅎㅎㅎ

**Comment by 2daebong** [comment]
http://stackoverflow.com/questions/41332179/how-to-push-all-files-in-a-folder-to-all-git-branches
처음으로 답변을 등록했다!!

**Comment by 2daebong** [comment]
http://stackoverflow.com/questions/41332179/how-to-push-all-files-in-a-folder-to-all-git-branches/41333887#41333887
내 답변이 채택 받았어!!!!!!!!!! 
reputation 16을 쌓았따 ㅎㅎㅎㅎㅎㅎㅎ 야쓰!
