### ISSUE TITLE
회원정보 입력 버그

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#67]
- 회원정보 입력란에 전화번호 입력시 제대로 입력이 안됨.
3자리 4자리 4자리를 입력해야하지만 모두 입력이 되지 않음.
확인 필요

**Comment by jason-hwang** [comment]
It has been resloved by 
https://github.com/Helibrothers/dico-server/commit/db95c5b4ba80fc1dfc70a8e20a1877cd3820722f
