### ISSUE TITLE
빈 주문 조회 리스트 노출 예외처리 필요

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#68]
<img width="318" alt="2016-12-27 11 29 13" src="https://cloud.githubusercontent.com/assets/13724323/21501591/64be1392-cc8c-11e6-9074-78ada3ebd0b1.png">

주문 내역이 없을 시 예외처리 필요.

참고
<img width="312" alt="2016-12-27 11 29 27" src="https://cloud.githubusercontent.com/assets/13724323/21501598/7771fc42-cc8c-11e6-84fa-8a7bfe445762.png">

**Comment by jason-hwang** [comment]
![screen shot 2017-01-04 at 12 24 35 am](https://cloud.githubusercontent.com/assets/4724172/21612382/4dce1cb2-d214-11e6-832c-b002073baad1.png)

업데이트 완료
