### ISSUE TITLE
itemDetail 페이지에서 장바구니 추가 기능

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#72]

**Comment by probitanima11** [comment]
상품디테일페이지에서 추가할 수 있도록 하기
<img width="416" alt="2016-12-29 7 44 31" src="https://cloud.githubusercontent.com/assets/4353846/21542170/3face168-cdff-11e6-837e-607ff4e4ed38.png">

**Comment by jason-hwang** [comment]
![screen shot 2017-01-03 at 11 46 41 pm](https://cloud.githubusercontent.com/assets/4724172/21611149/f12db698-d20e-11e6-8b93-3cb3e8b91b82.png)

- 장바구니 담기 및 이동하기 버튼 추가
- 메인 & 상품 디테일 페이지에서 함께 쓰기 위해 main.js 에서 addCart.js 따로 분리함

**Comment by probitanima11** [comment]
오 좋다!!
