### ISSUE TITLE
HTTPS 적용

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#78]
HTTPS 적용

단순히 적용하지 말고 알고 적용하자

HTTPS 개념부터 동작까지 
https://opentutorials.org/course/228/4894

공부중..ㅎㅎ

**Comment by 2daebong** [comment]
시간날때마다 이건 보고 있는데..

무료 CA 붙여서 테스트 해볼라고 했는데 
할려면.. 두가지가 먼저 되어야 되네.

1. 도메인에 대한 인증이기 때문에 도메인 확정 필요
    ㄴ 어드민은 서브 도메인으로 가는게 좋을듯. 
        - helifarm.com, admin.helifarm.com
2. 도메인의 소유주임을 검증하기 위한 해당 도메인으로 된 메일 필요 (이건 추후에도 고객센터용?으로 필요할수도)
    ㄴ 요거는 무료 웹메일 쓰면 될듯

이거 두개 된 다음에 진행하기로..ㅎㅎ

**Comment by jason-hwang** [comment]
넵 서브도메인으로 가도 될거같네요 ㅎㅎ

**Comment by jason-hwang** [comment]
참고 : http://adrenal.tistory.com/13

저도 잠깐 봤는데 https 인증서를 적용할 수 있는 부분은 다음과 같다고 하구요.

- ELB(Elastic Load Balancer)
- Web Server(Apache)
- Web Application Server (Tomcat)

향후에 ELB를 적용하는 것을 고려하면 (서비스 대박~!)
Apache나 Tomcat에 직접 설정하는 것보다 ELB에 SSL을 설정해두는 것이 장점이 많아 보이더라구요.

ELB를 적용하려면 AWS의 Route53을 통해 도메인을 설정해야 할 것 같은데 지금 도메인 서비스 어디꺼 사용하고 있나요??

Google에서 Progressive Web이라고 내세우는 컨셉이 있는데 (Web App이지만 App같은 성능과 UI를 지향)
핵심 기능인 Service Worker를 적용하려면 https가 필수라서 잠깐 찾아보다가 글을 남겨봅니다 ㅎㅎㅎ(잡담)
혹시 제가 잘못 이해하는 부분이 있으면 알려주셔도 돼요!!
Safari에서는 아직 Service Worker를 지원 하지 않지만... Progressive Web이라는게 꽤 재밌는 기능들이 많아서요!!

**Comment by 2daebong** [comment]
아주 좋네요
내가 잘 모르는 부분이 많은 것 같은데 ㅋㅋ (나는 https가 뭔지 왜 필요한지 어떻게 동작하는지가 중요하다고생각함)
아주 핵심을 찔러준거 같습니당 ㅋㅋ
먼저 질문에 답을 하자면
`지금 도메인 서비스 어디꺼 사용하고 있나요?`  -> 서비스 중인거는 알다시피 야채사요.com/ dicoadmin.com 이거 두개 인데요. 짐작하다시피 https를 사용하기 위해서는 인증하기 위한 도메인 등록이 필요하고, 그 과정에서 나는 도메인이 helifarm으로 변경될거라 생각해서 등록을 안한 상태입니다, ㅋㅋ

그리고 궁금한 점. google progressive web  이 내세우고 있는게 뭔지가 궁금하네요.

내가 이해하기로 https는 웹 상의 통신에서 공인된 인증서를 이용해서 서로 요청을 검증하는건데 이게 Google의 progressive web과 어떤 관계가 있는지 알려주면 좋을 것 같습니당

**Comment by jason-hwang** [comment]
사실 progressive web app(이하 PWA)은 우리가 https 적용하냐 마냐의 조건은 아니었구요.
향후 신기술 적용 가능성이나, Performance 측면에서 이점이 많아서 고려를 해봤어요. 
아이폰 유저는 아쉽게도 혜택을 못받을거 같지만... ㅎㅎ...

PWA에서 내세우는 여러 강점 중 Safe라는 항목이 있는데요 
([What is a Progressive Web app](https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/#what_is_a_progressive_web_app))
**Safe - Served via HTTPS to prevent snooping and to ensure content hasn't been tampered with.**

Service Worker라는 녀석의 핵심 기능이 다음과 같고, https를 적용하지 않을 경우 외부와의 통신에 누군가 간섭할 수도 있겠죠 (구글의 설명) (요녀석은 http 환경에서는 사용 불가)
- App Cache (png, js, css 등 네트웤 오프라인 상황에서도 리소스 사용 가능)
- Background Sync (오프라인 상황에서도 App이 정상 작동하는 것을 지원하고 온라인에 연결되면 그 동안 변경된 데이터를 Server와 동기화)
- Web Push(브라우저 내부적으로 Push를 받는 Service Worker Damon 생성)

그 외에도... https는 
- 암호화 장점 도 있고
- 혹시 모를 개인정보 유출에 대해 어느 정도 보험을 드는 셈이고
- 사용자로 하여금 안전하다는 인식을 심어줄 수도 있겠죠.
