### ISSUE TITLE
로그인 페이지 진입 후 이전 페이지로 돌아가기

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#79]
## 현재 상황
로그인 페이지에서 로그인 이 후 무조건 index페이지로 이동

## 하고싶은 것
로그인 페이지 진입 전 화면으로 이동 시켜주기

## 예상되는 문제
로그인 후 현재는 naverOauthCallback로 요청이 오도록 하는데 redirectUrl(로그인 이후로 이동할 url)을 param으로 보내고 받는 방법이 없음

## 예상 해결책
/naverOauthCallback에 redirectUrl을 포함해서 보내면 되지않을까 생각해봄
```
AS IS 
/naverOauthCallback

TO BE
/naverOauthCallback/{redirectUrl}
```

**Comment by jason-hwang** [comment]
으음 리다이렉션을 동적으로 붙이려면 예상되는 모든 url이 developer site에 등록되어야 하는데 현실적으로 불가능할듯... localStorage를 활용해서 히스토리 관리하는건 어떨지? 아니면 세션이나... ㅎㅎㅎ

**Comment by 2daebong** [comment]
히스토리 관리까지는 오버스펙일거 같은데..
`/naverOauthCallback/{redirectUrl}` 이거 대신 `/naverOauthCallback?rUrl={redirectUrl}`
이렇게해도 이슈가 있을까?

**Comment by jason-hwang** [comment]
음 그러니까 redirectUrl이 전부 사이트에 등록돼어있어야 로그인 할 수 잇어요

**Comment by probitanima11** [comment]
전 이부분을 몰라서 그냥 로그인 요청할때 redirectUrl을 파라미터로 넣어주면 다 되는줄 알았는데

로컬스토리지를 쓴다던지 다른 방식으로 기록을 남기는건 대봉햄말대로 오버스팩일꺼같네요

다시 검토해보겠습니다ㅎㅎ

**Comment by probitanima11** [comment]
빠른 피드백 감사요!
