### ISSUE TITLE
(Gzip) Http compression 적용하기

### ISSUE THREAD

**Issue by jason-hwang** [Helibrothers/dico-server#82]
- 현재 모든 Response가 compress되지 않은 채로 전송 되고 있음
- Gzip으로 compress해서 응답을 보낼 경우 60~70% 이상 용량 축소 가능
- js, css, html에 대해서만 압축 가능 (이미지는 불가)

**Comment by jason-hwang** [comment]
보충설명
http://www.javablog.fr/javaweb-gzip-compression-protocol-http-filter-gzipresponsewrapper-gzipresponsewrapper.html

나중에 CloudFront(캐시서버)를 함께 사용한다면 꼭 Origin에서 설정하지 않아도 각 엣지 로케이션에서 Compress 옵션 설정 가능하니.. 급한거 아니에요~

**Comment by jason-hwang** [comment]
생각해보니... 이미지를 제외한 전체 사이즈가 얼마 안돼서 굳이 Gzip 할 필요는 없을거 같네요....ㅎㅎ......

**Comment by 2daebong** [comment]
내가 알기로 프론트 코드를 압축하는게 용량 문제도 있지만 난독화 기능도 있으니 ㅎㅎ 
좋은 생각인듯 
급하진 않지만 차차 고민해볼사항인듯 ! 
굳

**Comment by jason-hwang** [comment]
Apache, tomcat 레벨에서 각각 적용하는 것으로 수정 완료
1) httpd.conf 에 mod_deflate 속성 주기
2) Server.xml에 compression = on 추가

참고 : https://www.clayharmon.com/words/posts/enabling-gzip-compression-on-ec2
