### ISSUE TITLE
tb_deilvery는 왜 tb_order와 분리되어있나요?

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#84]

**Comment by 2daebong** [comment]
두 테이블이 1:1 관계라 .. 사실 한 테이블에 둬도 문제는 없어
근데 주문정보에는 상태값을 가지고 있잖아 (status) 
주문 상태가 바뀔때마다 해당 row가 update 되어야 하는데 
그렇게 update 되는 테이블에는 주문에 관련된 최소한의 정보만 가지고 있는게 좋을것 같아서
한테이블에 있으면 주문상태가 바뀔때마다 (준비, 배송중, 완료) 배송 정보도 같이 업데이트 되니..

**Comment by probitanima11** [comment]
아하 그렇군요 궁금증 해결되어 클로즈 하겠습니다!
