### ISSUE TITLE
배송지 여러 곳 저장하게 할 수 있게 하면 어떨까요?

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#85]
쿠팡처럼 배송지이름+장소+전화번호을 한 세트로해서
UserInfo를 배송지정보로 해서 테이블 따로 두면 어떨까요?

<img width="600" alt="2017-01-09 12 38 42" src="https://cloud.githubusercontent.com/assets/4353846/21751062/04cd408a-d604-11e6-81e5-c9154f0d60b0.png">

**Comment by 2daebong** [comment]
오 많이 접하지만 생각치못한 부분이었네! ㅋㅋ
맥도날드 생각해보면 회사에서 먹을때 집에서 먹을때 배송지 두개 등록해두면 편하긴하지!

근데 우리가 판매하는 물품이 그렇게 여러곳에서 주문할 니즈가 많은가? 에 대한거도 생각해봐야 될 것 같음.

일단 급하진 않은데 고려해볼만한 사항인듯!

**Comment by probitanima11** [comment]
넵ㅋㅋ 맞아여 
한 계정으로 우리집이랑 가계랑 옆집 순이네까지 대신 주문을 할 수도 있을 꺼 같아서욯ㅎㅎㅎ

일단 천천히 해두됨으로 쌓아두겠습니다.

**Comment by jason-hwang** [comment]
니즈가 있을거 같긴해요 ㅋㅋ 옆집이랑 같이 구매한다던지... 그런게 있을려나 싶지만

**Comment by probitanima11** [comment]
하긴 그럴일은 많이 없을 수 있겠다ㅋㅋㅋ

이건 요구사항이 올라오면 그때 다시 여는걸로 합시다! close~
