### ISSUE TITLE
배송장소를 정확히 입력받게 하는 건 어떨까유?

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#86]
가까운 매장을 구하기 위해 입력받은 배송지 정보와 매장 정보들을 계산하기 위해
배송 장소를 정확히 입력 받는건 어떨까요?

AS IS 
String으로 받아옴

TO BE
아래 이미지 처럼 주소를 정확히 받아올 수 있도록...

**Comment by 2daebong** [comment]
일단 이미지가 없음.. ㅎㅎ
이거 처음에 @jason-hwang 이랑 같이 고민했던 부분인데
나중에는 네이버 주소 API 쓰면 이렇게 받아질듯 동시에 주변 매장도 보여주면 좋고
일단 초기 단계에서는 스트링으로 받아도 문제가 없다! 라고 해서 이렇게 한거 ㅎㅎ 
사실 주소를 주소로 받는다고 해도 그 사용자 집이 맞는지 검증되는건 아니니 ㅎㅎ

**Comment by probitanima11** [comment]
그쵸ㅋㅋㅋ 그 사용자 집 검증은 힘들죠ㅠㅠ

일단 시/도, 구/시/군, 읍/면/동 이렇게 받고 나머지 주소를 받으면
매장이 관리하고 있는 구역에 들어가는지 안들어가는지는 확실하게 구분될 꺼 같아서요ㅎㅎ

**Comment by jason-hwang** [comment]
어제 맥 딜리버리 앱 봤던 그 플로우가 제일 무난한듯 싶긴 하네요 ㅋㅋㅋ 주문 하기 직전에 배송받을 주소 확인하고 이상없으면 패쓰

**Comment by probitanima11** [comment]
@jason-hwang 
배송지에 따라서 상품이 달라질 수 있어서ㅜㅜ 배송지선택(혹은 매장)을 먼저 해야할 것 같은데...
이걸 어떻게 해야할 지 모르겠네ㅠㅠ

**Comment by probitanima11** [comment]
일단 플로우는 다른 이슈에서 생각하기로하고
배송지와 매장을 매칭하기 위해선 일단 동까지 선택할 수 있도록 해야할 것 같아서 진행하겠습니다!
