### ISSUE TITLE
사용자와 매장 매칭 하는 방법

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#87]
## 1. 사용자 배송지와 매장 정보의 GPS 값을 비교해 가장 가까운 매장 선택
- 매장을 선택하는 로직을 구현해야 함

## 2. 매장 별로 담당 구역을 지정해서 배송하도록 하기
- 지역별로 매장을 담당하는 부분을 구현해야 함

**Comment by 2daebong** [comment]
이번에 네이버 지도 v3 API가 나왔는데 그걸 쓰면 뭔가 재밋게 보여줄수 있을것 같은데 ㅎㅎ 
매장 별로 관리하는 영역을 표시하는데 용이할것같네.

참고 네이버 지도 오픈 API
https://navermaps.github.io/maps.js/docs/tutorial-digest.example.html

**Comment by probitanima11** [comment]
네ㅋㅋ 매장별로 담당 구역을 지정해서 할 수 있도록 하는게 좋을 것 같아요.
그럼 이 작업은 별도의 이슈에서 진행하겠습니다
