### ISSUE TITLE
상품 상세 페이지 CSS 입히기

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#9]
#1 추가작업.

**Comment by jason-hwang** [comment]
<img width="337" alt="screen shot 2016-12-12 at 12 34 06 am" src="https://cloud.githubusercontent.com/assets/4724172/21081093/ba942dba-c002-11e6-8946-27b3f79bdfc7.png">

상세 페이지 업데이트. 피드백 부탁 : )

**Comment by 2daebong** [comment]
일단 닫고 ㅎ 추후에 2차로 개선하던가 하자
