### ISSUE TITLE
페북로그인은 왜 필요한가요? + Admin 구분을 위한 방법!

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#93]
# 1. 페북 로그인은 왜 들어갔나요?
# 2. 매장관리자의 권한을 확인하는 방법은 무엇이 있을까요..

**Comment by probitanima11** [comment]
2번에 대한 저의 생각은(페북 로그인의 원인을 모르는 상태에서)
User 테이블에 role 컬럼을 추가해서 전체관리자, 매장관리자, 고객 로 구분해서 사용하는 방법을 우선 생각했습니다.

**Comment by 2daebong** [comment]
### 페북 로그인이 들어간 이유 
상품에서 업로드하는 이미지의 경우 AWS S3(Simple Storage Server)로 전달됨.
업로드하기 위한 인증방법은 여러가지가 있는데 그 중 페이스북 계정으로 인증하도록 연동한 것.

**Comment by probitanima11** [comment]
오ㅎㅎ 그러면 매장관리자도 페북계정으로 로긴을 해야겠군요!!

**Comment by 2daebong** [comment]
### 매장 관리자 권한 확인 방법
User 테이블에 role을 추가해도 되지만.
User가 엄청나게 많은경우 role 컬럼을 조건으로 관리자를 조회해야하는데.

차라리 어드민 계정을 관리하는 테이블을 따로 두고 거기에 페이스북 아이디를 넣으면 어떨까

**Comment by probitanima11** [comment]
@2daebong 오 좋은 아이디어내요!! 알겠습니당ㅎㅎ
사용자 계정 테이블과 관리자 테이블은 분리해서 진행하겠습니다.
