### ISSUE TITLE
어드민에서 상품 수정할 때 로그인 오류 발생

### ISSUE THREAD

**Issue by jason-hwang** [Helibrothers/dico-server#94]
- /admin/product에서 페북 로그인 후, 물품 정보 업데이트 할 때 네이버 로그인 안되어 있으면 인증 오류 발생

**Comment by jason-hwang** [comment]
@probitanima11 
LoginInterceptor에서 admin인 경우의 예외처리가 필요한듯 ㅎㅎ
아래처럼 필터 되는거 같은데 IS_LOGIN이 세션에 등록되는건 현재 네이버 로그인 할때만 등록돼서...!!

if (request.getSession().getAttribute(SessionConstant.IS_LOGIN) == null) {
	response.sendRedirect("/login");
	return false;
}

지금 admin의 각 페이지에서 정보 수정할 때
http://dicoadmin/api/{method name} 
요렇게 들어오는데 로그인 세션을 먼가 구분해야 할 듯

**Comment by probitanima11** [comment]
좋은것 같아유ㅋㅋㅋ
admin관련해서 고민해볼 필요가 있음ㅎㅎ

일단 저 안되는거는 수정해놓을께

**Comment by probitanima11** [comment]
나 페북 로그인이 안되서 이슈 확인이 좀 어렵넹 @_@

**Comment by probitanima11** [comment]
<img width="566" alt="2017-01-14 9 37 48" src="https://cloud.githubusercontent.com/assets/4353846/21950348/28787378-da3d-11e6-83bf-67433be8c24f.png">

**Comment by jason-hwang** [comment]
어라 왜 로긴이 안되지 어드민 등록되어 있는데

**Comment by jason-hwang** [comment]
developer.facebook.com에 myApp들어가볼래? 니 계정 펜딩되어잇음

![screen shot 2017-01-14 at 9 51 36 am](https://cloud.githubusercontent.com/assets/4724172/21950512/0b800eb4-da3f-11e6-81fd-7c55bf92dd65.png)

**Comment by probitanima11** [comment]
오ㅋㅋ 승인을 해야하는거였군! 감사감사

**Comment by probitanima11** [comment]
우선 쿠키를 통해 admin 로그인을 확인하는걸로 임시로 처리할께요

추후에 admin User 분리할 때 다시 제대로 처리하겠습니다.

**Comment by probitanima11** [comment]
이 외에도 
- /api/order/{userId}
- /api/order/{id} 
등 안되는 기능들이 있어서

https://github.com/Helibrothers/dico-server/pull/104 로 해결하였습니다.
