### ISSUE TITLE
디자이너 영입

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/dico-server#98]
- 재성이가 진행중
여기서 코멘트로 진행사항 업데이트 해줘 ㅎㅎ

**Comment by jason-hwang** [comment]
금주에 만나기로 했는데 아직 요일을 안정해서... 정해지면 업데이트 하겠습니다~

**Comment by jason-hwang** [comment]
이번주 일요일(22일)에 시간 된다고 해서 일단 알겠다고 했어요.

**Comment by 2daebong** [comment]
좋습니당 ㅎㅎㅎㅎ 그때 보여줄 자료있으면 여기도 올려주세요

**Comment by jason-hwang** [comment]
문서는 슬랙에 올릴께요

**Comment by jason-hwang** [comment]
1차 미팅 완료 : P
2차 미팅 준비 시 필요한 것들 정리
- 기획서 제작(지금 개발된것 베이스로, 그리고 미결된 부분들 정리하기)
- 협업 방법 결정하기 (GUI 가이드는 어떤식으로 전달할지)
- 기획서 완벽하게 정리 후 GUI 가이드 제작까지 1달~1달반 소요

2차 미팅때는 기획서 완성을 위해서 다 같이 미팅해야 할 것 같음.

**Comment by jason-hwang** [comment]
급한건 먼저

1. 앱 아이콘
2. 배너 이미지 3개
3. 소개 페이지

**Comment by probitanima11** [comment]
오늘 미팅 잘 끝난것 같습니다 :)

오늘 디자이너님이 집어준 포인트는 https://github.com/Helibrothers/dico-server/issues/117 에 정리하면 좋을 것 같아요
